/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 16.1 		*/
/*  Created On : 03-kwi-2023 03:03:53 				*/
/*  DBMS       : MSAccess 						*/
/* ---------------------------------------------------- */

ALTER TABLE [Analityk] DROP CONSTRAINT [FK_Analityk_Pracownik];

ALTER TABLE [DecyzjaAnalityczna] DROP CONSTRAINT [FK_DecyzjaAnalityczna_ZdolnoscKredytowa];

ALTER TABLE [DecyzjaAnalityczna] DROP CONSTRAINT [FK_DecyzjaAnalityczna_Opinia];

ALTER TABLE [DecyzjaAnalityczna] DROP CONSTRAINT [FK_DecyzjaAnalityczna_WarunkiUmowyDlaKlienta];

ALTER TABLE [DecyzjaAnalityczna] DROP CONSTRAINT [FK_DecyzjaAnalityczna_RaportZPodejrzanejTransakcji];

ALTER TABLE [Dyrektor] DROP CONSTRAINT [FK_Dyrektor_Pracownik];

ALTER TABLE [Opinia] DROP CONSTRAINT [FK_Opinia_Analityk];

ALTER TABLE [ParametrDoRaportuDziennegoDzialalnosciBanku] DROP CONSTRAINT [FK_ParametrDoRaportuDziennegoDzialalnosciBanku_Dyrektor];

ALTER TABLE [ParametrDoRaportuDziennegoDzialalnosciBanku] DROP CONSTRAINT [FK_ParametrDoRaportuDziennegoDzialalnosciBanku_RaportDziennyDzialalnosciBanku];

ALTER TABLE [Pracownik] DROP CONSTRAINT [FK_Pracownik_DaneTeleadresowe];

ALTER TABLE [PracownikDzialuObslugiKlienta] DROP CONSTRAINT [FK_Pracownik dzialu obslugi klienta_Pracownik];

ALTER TABLE [RaportDziennyDzialalnosciBanku] DROP CONSTRAINT [FK_RaportDziennyDzialalnosciBanku_RaportDziennyZPodejrzanychTransakcji];

ALTER TABLE [ScoringKredytowy] DROP CONSTRAINT [FK_ScoringKredytowy_DaneBik];

ALTER TABLE [WniosekKredytowy] DROP CONSTRAINT [FK_WniosekKredytowy_DaneTeleadresowe];

ALTER TABLE [WniosekKredytowy] DROP CONSTRAINT [FK_WniosekKredytowy_DecyzjaAnalityczna];

ALTER TABLE [WniosekKredytowy] DROP CONSTRAINT [FK_WniosekKredytowy_DokumentInformacjaOSytuacjiFinansowejKlienta];

ALTER TABLE [WniosekKredytowy] DROP CONSTRAINT [FK_WniosekKredytowy_DokumentUmowaKredytowa];

ALTER TABLE [WniosekKredytowy] DROP CONSTRAINT [FK_WniosekKredytowy_Klient];

ALTER TABLE [WniosekKredytowy] DROP CONSTRAINT [FK_WniosekKredytowy_Kredyt];

ALTER TABLE [WniosekKredytowy] DROP CONSTRAINT [FK_WniosekKredytowy_PracownikDzialuObslugiKlienta];

ALTER TABLE [WniosekKredytowy] DROP CONSTRAINT [FK_WniosekKredytowy_SytuacjaFinansowaKlienta];

ALTER TABLE [ZdolnoscKredytowa] DROP CONSTRAINT [FK_ZdolnoscKredytowa_ScoringKredytowy];

DROP TABLE [Analityk];

DROP TABLE [DaneBik];

DROP TABLE [DaneTeleadresowe];

DROP TABLE [DecyzjaAnalityczna];

DROP TABLE [DokumentInformacjaOSytuacjiFinansowejKlienta];

DROP TABLE [DokumentUmowaKredytowa];

DROP TABLE [Dyrektor];

DROP TABLE [Klient];

DROP TABLE [Kredyt];

DROP TABLE [Opinia];

DROP TABLE [ParametrDoRaportuDziennegoDzialalnosciBanku];

DROP TABLE [Pracownik];

DROP TABLE [PracownikDzialuObslugiKlienta];

DROP TABLE [RaportDziennyDzialalnosciBanku];

DROP TABLE [RaportDziennyZPodejrzanychTransakcji];

DROP TABLE [RaportZPodejrzanejTransakcji];

DROP TABLE [ScoringKredytowy];

DROP TABLE [SytuacjaFinansowaKlienta];

DROP TABLE [WarunkiUmowyDlaKlienta];

DROP TABLE [WniosekKredytowy];

DROP TABLE [ZdolnoscKredytowa];

CREATE TABLE [Analityk]
(
	[DzialAnalityczny] varchar NULL,
	[AnalitykID] Short NOT NULL
);

CREATE TABLE [DaneBik]
(
	[HistoriaBik] varchar NULL,
	[DaneBikID] Short NOT NULL
);

CREATE TABLE [DaneTeleadresowe]
(
	[IdDanych] varchar NULL,
	[KodPocztowy] varchar NULL,
	[Kraj] varchar NULL,
	[Miasto] varchar NULL,
	[Pesel] varchar NULL,
	[Telefon] varchar NULL,
	[DaneTeleadresoweID] Short NOT NULL
);

CREATE TABLE [DecyzjaAnalityczna]
(
	[DataWydania] varchar NULL,
	[UzasadnienieDecyzji] varchar NULL,
	[DecyzjaAnalitycznaID] Short NOT NULL,
	[ZdolnoscKredytowaID] Short NOT NULL,
	[OpiniaID] Short NOT NULL,
	[WarunkiUmowyDlaKlientaID] Short NULL,
	[RaportZPodejrzanejTransakcjiID] Short NULL
);

CREATE TABLE [DokumentInformacjaOSytuacjiFinansowejKlienta]
(
	[DataWgrania] varchar NULL,
	[TrescInformacji] varchar NULL,
	[DokumentInformacjaOSytuacjiFinansowejKlientaID] Short NOT NULL
);

CREATE TABLE [DokumentUmowaKredytowa]
(
	[DataPodpisania] varchar NULL,
	[DataWgrania] varchar NULL,
	[TrescUmowy] varchar NULL,
	[DokumentUmowaKredytowaID] Short NOT NULL
);

CREATE TABLE [Dyrektor]
(
	[DzialZarzadzania] varchar NULL,
	[DyrektorID] Short NOT NULL
);

CREATE TABLE [Klient]
(
	[Imie] varchar NULL,
	[Nazwisko] varchar NULL,
	[PeselKlienta] varchar NULL,
	[RodzajKlienta] varchar NULL,
	[KlientID] Short NOT NULL
);

CREATE TABLE [Kredyt]
(
	[OkresSplaty] varchar NULL,
	[RodzjRat] varchar NULL,
	[TypKredytu] varchar NULL,
	[KredytID] Short NOT NULL
);

CREATE TABLE [Opinia]
(
	[Opinia] varchar NULL,
	[Uzasadnienie] varchar NULL,
	[OpiniaID] Short NOT NULL,
	[AnalitykID] Short NULL
);

CREATE TABLE [ParametrDoRaportuDziennegoDzialalnosciBanku]
(
	[DataPodania] varchar NULL,
	[WartoscParametru] varchar NULL,
	[ParametrDoRaportuDziennegoDzialalnosciBankuID] varchar NOT NULL,
	[DyrektorID] Short NULL,
	[RaportDziennyDzialalnosciBankuID] Short NULL
);

CREATE TABLE [Pracownik]
(
	[DataZatrudnienia] varchar NULL,
	[DataZwolnienia] varchar NULL,
	[IdDzialu] varchar NULL,
	[IdPracownika] varchar NULL,
	[PracownikID] Short NOT NULL,
	[DaneTeleadresoweID] Short NOT NULL
);

CREATE TABLE [PracownikDzialuObslugiKlienta]
(
	[RodzajobslugiwanychKlientow] varchar NULL,
	[PracownikDzialuObslugiKlientaID] Short NOT NULL
);

CREATE TABLE [RaportDziennyDzialalnosciBanku]
(
	[DataGeneracji] varchar NULL,
	[TrescRaportuDzialalnosci] varchar NULL,
	[RaportDziennyDzialalnosciBankuID] Short NOT NULL,
	[RaportDziennyZPodejrzanychTransakcjiID] Short NOT NULL
);

CREATE TABLE [RaportDziennyZPodejrzanychTransakcji]
(
	[TrescRaportuZTransakcji] varchar NULL,
	[RaportDziennyZPodejrzanychTransakcjiID] Short NOT NULL
);

CREATE TABLE [RaportZPodejrzanejTransakcji]
(
	[DataNaruszenia] varchar NULL,
	[Naruszenie] varchar NULL,
	[RaportZPodejrzanejTransakcjiID] Short NOT NULL
);

CREATE TABLE [ScoringKredytowy]
(
	[WartoscScoringu] varchar NULL,
	[ScoringKredytowyID] Short NOT NULL,
	[DaneBikID] Short NOT NULL
);

CREATE TABLE [SytuacjaFinansowaKlienta]
(
	[StanCywilny] varchar NULL,
	[WysokoscDochodu] varchar NULL,
	[SytuacjaFinansowaKlientaID] Short NOT NULL
);

CREATE TABLE [WarunkiUmowyDlaKlienta]
(
	[Uzasadnienie] varchar NULL,
	[WarunkiUmowy] varchar NULL,
	[WarunkiUmowyDlaKlientaID] Short NOT NULL
);

CREATE TABLE [WniosekKredytowy]
(
	[DataOstatniejModyfikacji] varchar NULL,
	[DataOtwarcia] varchar NULL,
	[Status] varchar NULL,
	[WniosekKredytowyID] Short NOT NULL,
	[DaneTeleadresoweID] Short NOT NULL,
	[DecyzjaAnalitycznaID] Short NULL,
	[DokumentInformacjaOSytuacjiFinansowejKlientaID] Short NOT NULL,
	[DokumentUmowaKredytowaID] Short NOT NULL,
	[KlientID] Short NULL,
	[KredytID] Short NOT NULL,
	[PracownikDzialuObslugiKlientaID] Short NULL,
	[SytuacjaFinansowaKlientaID] Short NOT NULL
);

CREATE TABLE [ZdolnoscKredytowa]
(
	[DostepnaZdolnosc] varchar NULL,
	[ZdolnoscKredytowaID] Short NOT NULL,
	[ScoringKredytowyID] Short NOT NULL
);

ALTER TABLE [Analityk] ADD CONSTRAINT [PK_Analityk]
	PRIMARY KEY ([AnalitykID]);

ALTER TABLE [DaneBik] ADD CONSTRAINT [PK_DaneBik]
	PRIMARY KEY ([DaneBikID]);

ALTER TABLE [DaneTeleadresowe] ADD CONSTRAINT [PK_DaneTeleadresowe]
	PRIMARY KEY ([DaneTeleadresoweID]);

ALTER TABLE [DecyzjaAnalityczna] ADD CONSTRAINT [PK_DecyzjaAnalityczna]
	PRIMARY KEY ([DecyzjaAnalitycznaID]);

ALTER TABLE [DokumentInformacjaOSytuacjiFinansowejKlienta] ADD CONSTRAINT [PK_DokumentInformacjaOSytuacjiFinansowejKlienta]
	PRIMARY KEY ([DokumentInformacjaOSytuacjiFinansowejKlientaID]);

ALTER TABLE [DokumentUmowaKredytowa] ADD CONSTRAINT [PK_DokumentUmowaKredytowa]
	PRIMARY KEY ([DokumentUmowaKredytowaID]);

ALTER TABLE [Dyrektor] ADD CONSTRAINT [PK_Dyrektor]
	PRIMARY KEY ([DyrektorID]);

ALTER TABLE [Klient] ADD CONSTRAINT [PK_Klient]
	PRIMARY KEY ([KlientID]);

ALTER TABLE [Kredyt] ADD CONSTRAINT [PK_Kredyt]
	PRIMARY KEY ([KredytID]);

ALTER TABLE [Opinia] ADD CONSTRAINT [PK_Opinia]
	PRIMARY KEY ([OpiniaID]);

ALTER TABLE [ParametrDoRaportuDziennegoDzialalnosciBanku] ADD CONSTRAINT [PK_ParametrDoRaportuDziennegoDzialalnosciBanku]
	PRIMARY KEY ([ParametrDoRaportuDziennegoDzialalnosciBankuID]);

ALTER TABLE [Pracownik] ADD CONSTRAINT [PK_Pracownik]
	PRIMARY KEY ([PracownikID]);

ALTER TABLE [PracownikDzialuObslugiKlienta] ADD CONSTRAINT [PK_PracownikDzialuObslugiKlienta]
	PRIMARY KEY ([PracownikDzialuObslugiKlientaID]);

ALTER TABLE [RaportDziennyDzialalnosciBanku] ADD CONSTRAINT [PK_RaportDziennyDzialalnosciBanku]
	PRIMARY KEY ([RaportDziennyDzialalnosciBankuID]);

ALTER TABLE [RaportDziennyZPodejrzanychTransakcji] ADD CONSTRAINT [PK_RaportDziennyZPodejrzanychTransakcji]
	PRIMARY KEY ([RaportDziennyZPodejrzanychTransakcjiID]);

ALTER TABLE [RaportZPodejrzanejTransakcji] ADD CONSTRAINT [PK_RaportZPodejrzanejTransakcji]
	PRIMARY KEY ([RaportZPodejrzanejTransakcjiID]);

ALTER TABLE [ScoringKredytowy] ADD CONSTRAINT [PK_ScoringKredytowy]
	PRIMARY KEY ([ScoringKredytowyID]);

ALTER TABLE [SytuacjaFinansowaKlienta] ADD CONSTRAINT [PK_SytuacjaFinansowaKlienta]
	PRIMARY KEY ([SytuacjaFinansowaKlientaID]);

ALTER TABLE [WarunkiUmowyDlaKlienta] ADD CONSTRAINT [PK_WarunkiUmowyDlaKlienta]
	PRIMARY KEY ([WarunkiUmowyDlaKlientaID]);

ALTER TABLE [WniosekKredytowy] ADD CONSTRAINT [PK_WniosekKredytowy]
	PRIMARY KEY ([WniosekKredytowyID]);

ALTER TABLE [ZdolnoscKredytowa] ADD CONSTRAINT [PK_ZdolnoscKredytowa]
	PRIMARY KEY ([ZdolnoscKredytowaID]);

ALTER TABLE [Analityk] ADD CONSTRAINT [FK_Analityk_Pracownik]
	FOREIGN KEY ([AnalitykID]) REFERENCES [Pracownik] ([PracownikID]);

ALTER TABLE [DecyzjaAnalityczna] ADD CONSTRAINT [FK_DecyzjaAnalityczna_ZdolnoscKredytowa]
	FOREIGN KEY ([ZdolnoscKredytowaID]) REFERENCES [ZdolnoscKredytowa] ([ZdolnoscKredytowaID]);

ALTER TABLE [DecyzjaAnalityczna] ADD CONSTRAINT [FK_DecyzjaAnalityczna_Opinia]
	FOREIGN KEY ([OpiniaID]) REFERENCES [Opinia] ([OpiniaID]);

ALTER TABLE [DecyzjaAnalityczna] ADD CONSTRAINT [FK_DecyzjaAnalityczna_WarunkiUmowyDlaKlienta]
	FOREIGN KEY ([WarunkiUmowyDlaKlientaID]) REFERENCES [WarunkiUmowyDlaKlienta] ([WarunkiUmowyDlaKlientaID]);

ALTER TABLE [DecyzjaAnalityczna] ADD CONSTRAINT [FK_DecyzjaAnalityczna_RaportZPodejrzanejTransakcji]
	FOREIGN KEY ([RaportZPodejrzanejTransakcjiID]) REFERENCES [RaportZPodejrzanejTransakcji] ([RaportZPodejrzanejTransakcjiID]);

ALTER TABLE [Dyrektor] ADD CONSTRAINT [FK_Dyrektor_Pracownik]
	FOREIGN KEY ([DyrektorID]) REFERENCES [Pracownik] ([PracownikID]);

ALTER TABLE [Opinia] ADD CONSTRAINT [FK_Opinia_Analityk]
	FOREIGN KEY ([AnalitykID]) REFERENCES [Analityk] ([AnalitykID]);

ALTER TABLE [ParametrDoRaportuDziennegoDzialalnosciBanku] ADD CONSTRAINT [FK_ParametrDoRaportuDziennegoDzialalnosciBanku_Dyrektor]
	FOREIGN KEY ([DyrektorID]) REFERENCES [Dyrektor] ([DyrektorID]);

ALTER TABLE [ParametrDoRaportuDziennegoDzialalnosciBanku] ADD CONSTRAINT [FK_ParametrDoRaportuDziennegoDzialalnosciBanku_RaportDziennyDzialalnosciBanku]
	FOREIGN KEY ([RaportDziennyDzialalnosciBankuID]) REFERENCES [RaportDziennyDzialalnosciBanku] ([RaportDziennyDzialalnosciBankuID]);

ALTER TABLE [Pracownik] ADD CONSTRAINT [FK_Pracownik_DaneTeleadresowe]
	FOREIGN KEY ([DaneTeleadresoweID]) REFERENCES [DaneTeleadresowe] ([DaneTeleadresoweID]);

ALTER TABLE [PracownikDzialuObslugiKlienta] ADD CONSTRAINT [FK_Pracownik dzialu obslugi klienta_Pracownik]
	FOREIGN KEY ([PracownikDzialuObslugiKlientaID]) REFERENCES [Pracownik] ([PracownikID]);

ALTER TABLE [RaportDziennyDzialalnosciBanku] ADD CONSTRAINT [FK_RaportDziennyDzialalnosciBanku_RaportDziennyZPodejrzanychTransakcji]
	FOREIGN KEY ([RaportDziennyZPodejrzanychTransakcjiID]) REFERENCES [RaportDziennyZPodejrzanychTransakcji] ([RaportDziennyZPodejrzanychTransakcjiID]);

ALTER TABLE [ScoringKredytowy] ADD CONSTRAINT [FK_ScoringKredytowy_DaneBik]
	FOREIGN KEY ([DaneBikID]) REFERENCES [DaneBik] ([DaneBikID]);

ALTER TABLE [WniosekKredytowy] ADD CONSTRAINT [FK_WniosekKredytowy_DaneTeleadresowe]
	FOREIGN KEY ([DaneTeleadresoweID]) REFERENCES [DaneTeleadresowe] ([DaneTeleadresoweID]);

ALTER TABLE [WniosekKredytowy] ADD CONSTRAINT [FK_WniosekKredytowy_DecyzjaAnalityczna]
	FOREIGN KEY ([DecyzjaAnalitycznaID]) REFERENCES [DecyzjaAnalityczna] ([DecyzjaAnalitycznaID]);

ALTER TABLE [WniosekKredytowy] ADD CONSTRAINT [FK_WniosekKredytowy_DokumentInformacjaOSytuacjiFinansowejKlienta]
	FOREIGN KEY ([DokumentInformacjaOSytuacjiFinansowejKlientaID]) REFERENCES [DokumentInformacjaOSytuacjiFinansowejKlienta] ([DokumentInformacjaOSytuacjiFinansowejKlientaID]);

ALTER TABLE [WniosekKredytowy] ADD CONSTRAINT [FK_WniosekKredytowy_DokumentUmowaKredytowa]
	FOREIGN KEY ([DokumentUmowaKredytowaID]) REFERENCES [DokumentUmowaKredytowa] ([DokumentUmowaKredytowaID]);

ALTER TABLE [WniosekKredytowy] ADD CONSTRAINT [FK_WniosekKredytowy_Klient]
	FOREIGN KEY ([KlientID]) REFERENCES [Klient] ([KlientID]);

ALTER TABLE [WniosekKredytowy] ADD CONSTRAINT [FK_WniosekKredytowy_Kredyt]
	FOREIGN KEY ([KredytID]) REFERENCES [Kredyt] ([KredytID]);

ALTER TABLE [WniosekKredytowy] ADD CONSTRAINT [FK_WniosekKredytowy_PracownikDzialuObslugiKlienta]
	FOREIGN KEY ([PracownikDzialuObslugiKlientaID]) REFERENCES [PracownikDzialuObslugiKlienta] ([PracownikDzialuObslugiKlientaID]);

ALTER TABLE [WniosekKredytowy] ADD CONSTRAINT [FK_WniosekKredytowy_SytuacjaFinansowaKlienta]
	FOREIGN KEY ([SytuacjaFinansowaKlientaID]) REFERENCES [SytuacjaFinansowaKlienta] ([SytuacjaFinansowaKlientaID]);

ALTER TABLE [ZdolnoscKredytowa] ADD CONSTRAINT [FK_ZdolnoscKredytowa_ScoringKredytowy]
	FOREIGN KEY ([ScoringKredytowyID]) REFERENCES [ScoringKredytowy] ([ScoringKredytowyID]);
