///////////////////////////////////////////////////////////
//  Formularz_Przekazraportdzienny.cs
//  Implementation of the Class Formularz_Przekazraportdzienny
//  Generated by Enterprise Architect
//  Created on:      03-kwi-2023 02:06:57
//  Original author: Marcin Kurzawski
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



namespace Interfejsy {
	public class Formularz_Przekazraportdzienny {

		private char data;

		public Formularz_Przekazraportdzienny(){

		}

		~Formularz_Przekazraportdzienny(){

		}

		public void przekazRaportDzienny(){

		}

		public Ster_Przekazraportdzienny Ster_Przekazraportdzienny{
			get{
				return m_Ster_Przekazraportdzienny;
			}
			set{
				m_Ster_Przekazraportdzienny = value;
			}
		}

	}//end Formularz_Przekazraportdzienny

}//end namespace Interfejsy