///////////////////////////////////////////////////////////
//  Formularz_ZapiszPlikUmowaKredytowa.cs
//  Implementation of the Class Formularz_ZapiszPlikUmowaKredytowa
//  Generated by Enterprise Architect
//  Created on:      03-kwi-2023 02:08:04
//  Original author: Marcin Kurzawski
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



namespace Interfejsy {
	public class Formularz_ZapiszPlikUmowaKredytowa {

		private int idWniosek;
		private char Plik umowa kredytowa;

		public Formularz_ZapiszPlikUmowaKredytowa(){

		}

		~Formularz_ZapiszPlikUmowaKredytowa(){

		}

		public void plikUmowaKredytowa(){

		}

		public Ster_ZapiszPlikUmowaKredytowa Ster_ZapiszPlikUmowaKredytowa{
			get{
				return m_Ster_ZapiszPlikUmowaKredytowa;
			}
			set{
				m_Ster_ZapiszPlikUmowaKredytowa = value;
			}
		}

	}//end Formularz_ZapiszPlikUmowaKredytowa

}//end namespace Interfejsy