///////////////////////////////////////////////////////////
//  Forumlarz_Obliczzdolnosckredytowa.cs
//  Implementation of the Class Forumlarz_Obliczzdolnosckredytowa
//  Generated by Enterprise Architect
//  Created on:      03-kwi-2023 02:08:15
//  Original author: Marcin Kurzawski
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



namespace Interfejsy {
	public class Forumlarz_Obliczzdolnosckredytowa {

		private int idWniosek;

		public Forumlarz_Obliczzdolnosckredytowa(){

		}

		~Forumlarz_Obliczzdolnosckredytowa(){

		}

		public void obliczZdolnoscKredytowa(){

		}

		public Ster_Obliczzdolnosckredytowa Ster_Obliczzdolnosckredytowa{
			get{
				return m_Ster_Obliczzdolnosckredytowa;
			}
			set{
				m_Ster_Obliczzdolnosckredytowa = value;
			}
		}

	}//end Forumlarz_Obliczzdolnosckredytowa

}//end namespace Interfejsy