///////////////////////////////////////////////////////////
//  Formularz_PotwierdzWarunkiKredytu.cs
//  Implementation of the Class Formularz_PotwierdzWarunkiKredytu
//  Generated by Enterprise Architect
//  Created on:      03-kwi-2023 02:06:41
//  Original author: Marcin Kurzawski
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



namespace Interfejsy {
	public class Formularz_PotwierdzWarunkiKredytu {

		private char decyzja;
		private int idWNiosek;

		public Formularz_PotwierdzWarunkiKredytu(){

		}

		~Formularz_PotwierdzWarunkiKredytu(){

		}

		public void potwierdzWarunkiKredytu(){

		}

		public Ster_PotwierdzWarunkiKredytu Ster_PotwierdzWarunkiKredytu{
			get{
				return m_Ster_PotwierdzWarunkiKredytu;
			}
			set{
				m_Ster_PotwierdzWarunkiKredytu = value;
			}
		}

	}//end Formularz_PotwierdzWarunkiKredytu

}//end namespace Interfejsy