///////////////////////////////////////////////////////////
//  Formularz_ObliczScoringKredytowy.cs
//  Implementation of the Class Formularz_ObliczScoringKredytowy
//  Generated by Enterprise Architect
//  Created on:      03-kwi-2023 02:06:16
//  Original author: Marcin Kurzawski
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



namespace Interfejsy {
	public class Formularz_ObliczScoringKredytowy {

		private int idWniosek;

		public Formularz_ObliczScoringKredytowy(){

		}

		~Formularz_ObliczScoringKredytowy(){

		}

		public void obliczScoring(){

		}

		public Ster_ObliczScoringKredytowy Ster_ObliczScoringKredytowy{
			get{
				return m_Ster_ObliczScoringKredytowy;
			}
			set{
				m_Ster_ObliczScoringKredytowy = value;
			}
		}

	}//end Formularz_ObliczScoringKredytowy

}//end namespace Interfejsy