///////////////////////////////////////////////////////////
//  Formularz_OtworzWniosek.cs
//  Implementation of the Class Formularz_OtworzWniosek
//  Generated by Enterprise Architect
//  Created on:      03-kwi-2023 02:06:35
//  Original author: Marcin Kurzawski
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



namespace Interfejsy {
	public class Formularz_OtworzWniosek {

		private char idKLient;

		public Formularz_OtworzWniosek(){

		}

		~Formularz_OtworzWniosek(){

		}

		public void otworzWniosek(){

		}

		public Ster_OtworzWniosek Ster_OtworzWniosek{
			get{
				return m_Ster_OtworzWniosek;
			}
			set{
				m_Ster_OtworzWniosek = value;
			}
		}

	}//end Formularz_OtworzWniosek

}//end namespace Interfejsy