///////////////////////////////////////////////////////////
//  Formularz_ZapiszDaneoSytuacjiFinansowejKlienta.cs
//  Implementation of the Class Formularz_ZapiszDaneoSytuacjiFinansowejKlienta
//  Generated by Enterprise Architect
//  Created on:      03-kwi-2023 02:07:51
//  Original author: Marcin Kurzawski
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



namespace Interfejsy {
	public class Formularz_ZapiszDaneoSytuacjiFinansowejKlienta {

		private int idWniosek;
		private int informacje;

		public Formularz_ZapiszDaneoSytuacjiFinansowejKlienta(){

		}

		~Formularz_ZapiszDaneoSytuacjiFinansowejKlienta(){

		}

		public Ster_ZapiszDaneoSytuacjiFinansowejKlienta Ster_ZapiszDaneoSytuacjiFinansowejKlienta{
			get{
				return m_Ster_ZapiszDaneoSytuacjiFinansowejKlienta;
			}
			set{
				m_Ster_ZapiszDaneoSytuacjiFinansowejKlienta = value;
			}
		}

		public void zapiszDaneOSytuacjiFinansowej(){

		}

	}//end Formularz_ZapiszDaneoSytuacjiFinansowejKlienta

}//end namespace Interfejsy