///////////////////////////////////////////////////////////
//  Formularz_ZamknijWniosek.cs
//  Implementation of the Class Formularz_ZamknijWniosek
//  Generated by Enterprise Architect
//  Created on:      03-kwi-2023 02:07:32
//  Original author: Marcin Kurzawski
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



namespace Interfejsy {
	public class Formularz_ZamknijWniosek {

		private int idWniosek;

		public Formularz_ZamknijWniosek(){

		}

		~Formularz_ZamknijWniosek(){

		}

		public Ster_ZamknijWniosek Ster_ZamknijWniosek{
			get{
				return m_Ster_ZamknijWniosek;
			}
			set{
				m_Ster_ZamknijWniosek = value;
			}
		}

		public void zamknijWniosek(){

		}

	}//end Formularz_ZamknijWniosek

}//end namespace Interfejsy