///////////////////////////////////////////////////////////
//  Formularz_ZapiszAktualneInformacjeoKliencie.cs
//  Implementation of the Class Formularz_ZapiszAktualneInformacjeoKliencie
//  Generated by Enterprise Architect
//  Created on:      03-kwi-2023 02:07:38
//  Original author: Marcin Kurzawski
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



namespace Interfejsy {
	public class Formularz_ZapiszAktualneInformacjeoKliencie {

		private int idWniosek;
		private char informacje;
		private char Nazwisko;

		public Formularz_ZapiszAktualneInformacjeoKliencie(){

		}

		~Formularz_ZapiszAktualneInformacjeoKliencie(){

		}

		public Ster_ZapiszAktualneInformacjeoKliencie Ster_ZapiszAktualneInformacjeoKliencie{
			get{
				return m_Ster_ZapiszAktualneInformacjeoKliencie;
			}
			set{
				m_Ster_ZapiszAktualneInformacjeoKliencie = value;
			}
		}

		public void zapiszDaneOKliencie(){

		}

	}//end Formularz_ZapiszAktualneInformacjeoKliencie

}//end namespace Interfejsy