///////////////////////////////////////////////////////////
//  Formularz_ZapiszDaneoKredycie.cs
//  Implementation of the Class Formularz_ZapiszDaneoKredycie
//  Generated by Enterprise Architect
//  Created on:      03-kwi-2023 02:07:45
//  Original author: Marcin Kurzawski
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



namespace Interfejsy {
	public class Formularz_ZapiszDaneoKredycie {

		private char idWniosek;
		private char informacje;

		public Formularz_ZapiszDaneoKredycie(){

		}

		~Formularz_ZapiszDaneoKredycie(){

		}

		public Ster_ZapiszDaneoKredycie Ster_ZapiszDaneoKredycie{
			get{
				return m_Ster_ZapiszDaneoKredycie;
			}
			set{
				m_Ster_ZapiszDaneoKredycie = value;
			}
		}

		public void zapiszDaneOKredycie(){

		}

	}//end Formularz_ZapiszDaneoKredycie

}//end namespace Interfejsy