///////////////////////////////////////////////////////////
//  Formularz_Zarzadzajcodziennymraportem.cs
//  Implementation of the Class Formularz_Zarzadzajcodziennymraportem
//  Generated by Enterprise Architect
//  Created on:      03-kwi-2023 02:08:10
//  Original author: Marcin Kurzawski
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



namespace Interfejsy {
	public class Formularz_Zarzadzajcodziennymraportem {

		private char data;

		public Formularz_Zarzadzajcodziennymraportem(){

		}

		~Formularz_Zarzadzajcodziennymraportem(){

		}

		public Ster_Zarzadzajcodziennymraportem Ster_Zarzadzajcodziennymraportem{
			get{
				return m_Ster_Zarzadzajcodziennymraportem;
			}
			set{
				m_Ster_Zarzadzajcodziennymraportem = value;
			}
		}

		public void zarzadzajRaportemDziennym(){

		}

	}//end Formularz_Zarzadzajcodziennymraportem

}//end namespace Interfejsy