///////////////////////////////////////////////////////////
//  Formularz_ZapiszPlikInformacjeoSytuacjiFinansowejKlienta.cs
//  Implementation of the Class Formularz_ZapiszPlikInformacjeoSytuacjiFinansowejKlienta
//  Generated by Enterprise Architect
//  Created on:      03-kwi-2023 02:07:59
//  Original author: Marcin Kurzawski
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



namespace Interfejsy {
	public class Formularz_ZapiszPlikInformacjeoSytuacjiFinansowejKlienta {

		private int idWNiosek;
		private char Plik umowa kredytowa;

		public Formularz_ZapiszPlikInformacjeoSytuacjiFinansowejKlienta(){

		}

		~Formularz_ZapiszPlikInformacjeoSytuacjiFinansowejKlienta(){

		}

		public Dokument informacja o sytuacji finansowej klienta Dokument informacja o sytuacji finansowej klienta{
			get{
				return m_Dokument informacja o sytuacji finansowej klienta;
			}
			set{
				m_Dokument informacja o sytuacji finansowej klienta = value;
			}
		}

		public void zapiszPlikInformacjeOSytuacjiFinansowej(){

		}

	}//end Formularz_ZapiszPlikInformacjeoSytuacjiFinansowejKlienta

}//end namespace Interfejsy