///////////////////////////////////////////////////////////
//  Forumlarz_Wygenerujraportdladyrektora.cs
//  Implementation of the Class Forumlarz_Wygenerujraportdladyrektora
//  Generated by Enterprise Architect
//  Created on:      03-kwi-2023 02:08:38
//  Original author: Marcin Kurzawski
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



namespace Interfejsy {
	public class Forumlarz_Wygenerujraportdladyrektora {

		private int idWniosek;

		public Forumlarz_Wygenerujraportdladyrektora(){

		}

		~Forumlarz_Wygenerujraportdladyrektora(){

		}

		public Ster_Wygenerujraportdladyrektora Ster_Wygenerujraportdladyrektora{
			get{
				return m_Ster_Wygenerujraportdladyrektora;
			}
			set{
				m_Ster_Wygenerujraportdladyrektora = value;
			}
		}

		public void wygenerujRaportDlaDyrektora(){

		}

	}//end Forumlarz_Wygenerujraportdladyrektora

}//end namespace Interfejsy