///////////////////////////////////////////////////////////
//  Forumlarz_PobierzdanezBIK.cs
//  Implementation of the Class Forumlarz_PobierzdanezBIK
//  Generated by Enterprise Architect
//  Created on:      03-kwi-2023 02:08:21
//  Original author: Marcin Kurzawski
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



namespace Interfejsy {
	public class Forumlarz_PobierzdanezBIK {

		private int idWNiosek;

		public Forumlarz_PobierzdanezBIK(){

		}

		~Forumlarz_PobierzdanezBIK(){

		}

		public void pobierzDaneZBik(){

		}

		public Ster_PobierzdanezBIK Ster_PobierzdanezBIK{
			get{
				return m_Ster_PobierzdanezBIK;
			}
			set{
				m_Ster_PobierzdanezBIK = value;
			}
		}

	}//end Forumlarz_PobierzdanezBIK

}//end namespace Interfejsy