///////////////////////////////////////////////////////////
//  Forumlarz_Wygenerujinformacjedlaklienta.cs
//  Implementation of the Class Forumlarz_Wygenerujinformacjedlaklienta
//  Generated by Enterprise Architect
//  Created on:      03-kwi-2023 02:08:32
//  Original author: Marcin Kurzawski
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



namespace Interfejsy {
	public class Forumlarz_Wygenerujinformacjedlaklienta {

		private int idWniosek;

		public Forumlarz_Wygenerujinformacjedlaklienta(){

		}

		~Forumlarz_Wygenerujinformacjedlaklienta(){

		}

		public Ster_Wygenerujinformacjedlaklienta Ster_Wygenerujinformacjedlaklienta{
			get{
				return m_Ster_Wygenerujinformacjedlaklienta;
			}
			set{
				m_Ster_Wygenerujinformacjedlaklienta = value;
			}
		}

		public void wygenerujInformacjeDlaKlienta(){

		}

	}//end Forumlarz_Wygenerujinformacjedlaklienta

}//end namespace Interfejsy