///////////////////////////////////////////////////////////
//  Forumlarz_Przeprowadzanalizepodejrzanejtransakcji.cs
//  Implementation of the Class Forumlarz_Przeprowadzanalizepodejrzanejtransakcji
//  Generated by Enterprise Architect
//  Created on:      03-kwi-2023 02:08:26
//  Original author: Marcin Kurzawski
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



namespace Interfejsy {
	public class Forumlarz_Przeprowadzanalizepodejrzanejtransakcji {

		private int idWniosek;

		public Forumlarz_Przeprowadzanalizepodejrzanejtransakcji(){

		}

		~Forumlarz_Przeprowadzanalizepodejrzanejtransakcji(){

		}

		public void przeprowadzAnalizePodejrzanejTransakcji(){

		}

		public Ster_Przeprowadzanalizepodejrzanejtransakcji Ster_Przeprowadzanalizepodejrzanejtransakcji{
			get{
				return m_Ster_Przeprowadzanalizepodejrzanejtransakcji;
			}
			set{
				m_Ster_Przeprowadzanalizepodejrzanejtransakcji = value;
			}
		}

	}//end Forumlarz_Przeprowadzanalizepodejrzanejtransakcji

}//end namespace Interfejsy