///////////////////////////////////////////////////////////
//  Ster_Przekazraportdzienny.cs
//  Implementation of the Class Ster_Przekazraportdzienny
//  Generated by Enterprise Architect
//  Created on:      06-kwi-2023 23:56:50
//  Original author: Marcin Kurzawski
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public class Ster_Przekazraportdzienny {

	private char data;

	public Ster_Przekazraportdzienny(){

	}

	~Ster_Przekazraportdzienny(){

	}

	public void przekazRaportDzienny(){

	}

	public Raport dzienny dzialalnosci banku Raport dzienny dzialalnosci banku{
		get{
			return m_Raport dzienny dzialalnosci banku;
		}
		set{
			m_Raport dzienny dzialalnosci banku = value;
		}
	}

}//end Ster_Przekazraportdzienny