///////////////////////////////////////////////////////////
//  Ster_ZapiszAktualneInformacjeoKliencie.cs
//  Implementation of the Class Ster_ZapiszAktualneInformacjeoKliencie
//  Generated by Enterprise Architect
//  Created on:      06-kwi-2023 23:57:29
//  Original author: Marcin Kurzawski
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public class Ster_ZapiszAktualneInformacjeoKliencie {

	private char idWniosek;
	private char informacje;
	private char Nazwisko;
	private char Pesel;

	public Ster_ZapiszAktualneInformacjeoKliencie(){

	}

	~Ster_ZapiszAktualneInformacjeoKliencie(){

	}

	public Dane teleadresowe Dane teleadresowe{
		get{
			return m_Dane teleadresowe;
		}
		set{
			m_Dane teleadresowe = value;
		}
	}

	public void zapiszDaneOKliencie(){

	}

}//end Ster_ZapiszAktualneInformacjeoKliencie