///////////////////////////////////////////////////////////
//  Ster_ZaakceptujRaport.cs
//  Implementation of the Class Ster_ZaakceptujRaport
//  Generated by Enterprise Architect
//  Created on:      06-kwi-2023 23:57:20
//  Original author: Marcin Kurzawski
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public class Ster_ZaakceptujRaport {

	private int data;
	private char Dodatkowy parametr do raportu;

	public Ster_ZaakceptujRaport(){

	}

	~Ster_ZaakceptujRaport(){

	}

	public Parametr do raportu dziennego dzialalnosci banku Parametr do raportu dziennego dzialalnosci banku{
		get{
			return m_Parametr do raportu dziennego dzialalnosci banku;
		}
		set{
			m_Parametr do raportu dziennego dzialalnosci banku = value;
		}
	}

	public void PodajDaneDoRaportu(){

	}

	public Raport dzienny dzialalnosci banku Raport dzienny dzialalnosci banku{
		get{
			return m_Raport dzienny dzialalnosci banku;
		}
		set{
			m_Raport dzienny dzialalnosci banku = value;
		}
	}

	public void wczytajRaportDzienny(){

	}

}//end Ster_ZaakceptujRaport