///////////////////////////////////////////////////////////
//  Ster_PrzejrzyjRaportzPodejrzanejTransakcji.cs
//  Implementation of the Class Ster_PrzejrzyjRaportzPodejrzanejTransakcji
//  Generated by Enterprise Architect
//  Created on:      06-kwi-2023 23:56:45
//  Original author: Marcin Kurzawski
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public class Ster_PrzejrzyjRaportzPodejrzanejTransakcji {

	private char Naruszenie;

	public Ster_PrzejrzyjRaportzPodejrzanejTransakcji(){

	}

	~Ster_PrzejrzyjRaportzPodejrzanejTransakcji(){

	}

	public void przejrzyjRaportZPodejrzanejTransakcji(){

	}

	public Raport z podejrzanej transakcji Raport z podejrzanej transakcji{
		get{
			return m_Raport z podejrzanej transakcji;
		}
		set{
			m_Raport z podejrzanej transakcji = value;
		}
	}

}//end Ster_PrzejrzyjRaportzPodejrzanejTransakcji