///////////////////////////////////////////////////////////
//  Ster_PobierzdanezBIK.cs
//  Implementation of the Class Ster_PobierzdanezBIK
//  Generated by Enterprise Architect
//  Created on:      06-kwi-2023 23:56:35
//  Original author: Marcin Kurzawski
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public class Ster_PobierzdanezBIK {

	private char idKlient;

	public Ster_PobierzdanezBIK(){

	}

	~Ster_PobierzdanezBIK(){

	}

	public Dane BIK Dane BIK{
		get{
			return m_Dane BIK;
		}
		set{
			m_Dane BIK = value;
		}
	}

	public void pobierzDaneZBik(){

	}

}//end Ster_PobierzdanezBIK