///////////////////////////////////////////////////////////
//  Ster_Wygenerujinformacjedlaklienta.cs
//  Implementation of the Class Ster_Wygenerujinformacjedlaklienta
//  Generated by Enterprise Architect
//  Created on:      06-kwi-2023 23:57:08
//  Original author: Marcin Kurzawski
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public class Ster_Wygenerujinformacjedlaklienta {

	private int idWniosek;

	public Ster_Wygenerujinformacjedlaklienta(){

	}

	~Ster_Wygenerujinformacjedlaklienta(){

	}

	public Warunki umowy dla klienta Warunki umowy dla klienta{
		get{
			return m_Warunki umowy dla klienta;
		}
		set{
			m_Warunki umowy dla klienta = value;
		}
	}

	public void wczytajOpinie(){

	}

	public void wygenerujInformacjeDlaKlienta(){

	}

}//end Ster_Wygenerujinformacjedlaklienta