///////////////////////////////////////////////////////////
//  Ster_ZapiszPlikUmowaKredytowa.cs
//  Implementation of the Class Ster_ZapiszPlikUmowaKredytowa
//  Generated by Enterprise Architect
//  Created on:      06-kwi-2023 23:57:43
//  Original author: Marcin Kurzawski
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public class Ster_ZapiszPlikUmowaKredytowa {

	private int idWNiosek;
	private char Plik umowa kredytowa;

	public Ster_ZapiszPlikUmowaKredytowa(){

	}

	~Ster_ZapiszPlikUmowaKredytowa(){

	}

	public void zapiszPlikUmowaKredytowa(){

	}

}//end Ster_ZapiszPlikUmowaKredytowa