///////////////////////////////////////////////////////////
//  Ster_ZamknijWniosek.cs
//  Implementation of the Class Ster_ZamknijWniosek
//  Generated by Enterprise Architect
//  Created on:      06-kwi-2023 23:57:25
//  Original author: Marcin Kurzawski
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public class Ster_ZamknijWniosek {

	private int idWniosek;

	public Ster_ZamknijWniosek(){

	}

	~Ster_ZamknijWniosek(){

	}

	public Wniosek kredytowy Wniosek kredytowy{
		get{
			return m_Wniosek kredytowy;
		}
		set{
			m_Wniosek kredytowy = value;
		}
	}

	public void zamknijWniosek(){

	}

}//end Ster_ZamknijWniosek