///////////////////////////////////////////////////////////
//  Ster_Wydajopinieanalityczna.cs
//  Implementation of the Class Ster_Wydajopinieanalityczna
//  Generated by Enterprise Architect
//  Created on:      06-kwi-2023 23:57:04
//  Original author: Marcin Kurzawski
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using Dane;
public class Ster_Wydajopinieanalityczna {

	private char idWniosek;
	private char opinia;

	public Ster_Wydajopinieanalityczna(){

	}

	~Ster_Wydajopinieanalityczna(){

	}

	public Opinia Opinia{
		get{
			return opinia;
		}
		set{
			opinia = value;
		}
	}

	public void wydajOpinieAnalityczna(){

	}

}//end Ster_Wydajopinieanalityczna