///////////////////////////////////////////////////////////
//  Ster_Zarzadzajcodziennymraportem.cs
//  Implementation of the Class Ster_Zarzadzajcodziennymraportem
//  Generated by Enterprise Architect
//  Created on:      06-kwi-2023 23:57:48
//  Original author: Marcin Kurzawski
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public class Ster_Zarzadzajcodziennymraportem {

	private char data;

	public Ster_Zarzadzajcodziennymraportem(){

	}

	~Ster_Zarzadzajcodziennymraportem(){

	}

	public Raport dzienny dzialalnosci banku Raport dzienny dzialalnosci banku{
		get{
			return m_Raport dzienny dzialalnosci banku;
		}
		set{
			m_Raport dzienny dzialalnosci banku = value;
		}
	}

	public Raport dzienny z podejrzanych transakcji Raport dzienny z podejrzanych transakcji{
		get{
			return m_Raport dzienny z podejrzanych transakcji;
		}
		set{
			m_Raport dzienny z podejrzanych transakcji = value;
		}
	}

	public void zarzadzajRaportemDziennym(){

	}

}//end Ster_Zarzadzajcodziennymraportem