///////////////////////////////////////////////////////////
//  Ster_Wygenerujraportdladyrektora.cs
//  Implementation of the Class Ster_Wygenerujraportdladyrektora
//  Generated by Enterprise Architect
//  Created on:      06-kwi-2023 23:57:12
//  Original author: Marcin Kurzawski
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public class Ster_Wygenerujraportdladyrektora {

	private char idWniosek;

	public Ster_Wygenerujraportdladyrektora(){

	}

	~Ster_Wygenerujraportdladyrektora(){

	}

	public Raport z podejrzanej transakcji Raport z podejrzanej transakcji{
		get{
			return m_Raport z podejrzanej transakcji;
		}
		set{
			m_Raport z podejrzanej transakcji = value;
		}
	}

	public void wygenerujRaportDlaDyrektora(){

	}

}//end Ster_Wygenerujraportdladyrektora