///////////////////////////////////////////////////////////
//  Ster_OtworzWniosek.cs
//  Implementation of the Class Ster_OtworzWniosek
//  Generated by Enterprise Architect
//  Created on:      06-kwi-2023 23:56:27
//  Original author: Marcin Kurzawski
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public class Ster_OtworzWniosek {

	private char idKlient;

	public Ster_OtworzWniosek(){

	}

	~Ster_OtworzWniosek(){

	}

	public void otworzWNiosek(){

	}

	public Wniosek kredytowy Wniosek kredytowy{
		get{
			return m_Wniosek kredytowy;
		}
		set{
			m_Wniosek kredytowy = value;
		}
	}

}//end Ster_OtworzWniosek