///////////////////////////////////////////////////////////
//  Ster_Przeprowadzanalizepodejrzanejtransakcji.cs
//  Implementation of the Class Ster_Przeprowadzanalizepodejrzanejtransakcji
//  Generated by Enterprise Architect
//  Created on:      06-kwi-2023 23:56:58
//  Original author: Marcin Kurzawski
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public class Ster_Przeprowadzanalizepodejrzanejtransakcji {

	private char idWniosek;

	public Ster_Przeprowadzanalizepodejrzanejtransakcji(){

	}

	~Ster_Przeprowadzanalizepodejrzanejtransakcji(){

	}

	public void przeprowadzAnalizePodejrzanejTransakcji(){

	}

	public Raport z podejrzanej transakcji Raport z podejrzanej transakcji{
		get{
			return m_Raport z podejrzanej transakcji;
		}
		set{
			m_Raport z podejrzanej transakcji = value;
		}
	}

}//end Ster_Przeprowadzanalizepodejrzanejtransakcji