///////////////////////////////////////////////////////////
//  Formularz_PrzejrzyjRaportzPodejrzanejTransakcji.cs
//  Implementation of the Class Formularz_PrzejrzyjRaportzPodejrzanejTransakcji
//  Generated by Enterprise Architect
//  Created on:      03-kwi-2023 02:06:47
//  Original author: Marcin Kurzawski
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



namespace Interfejsy {
	public class Formularz_PrzejrzyjRaportzPodejrzanejTransakcji {

		private char idWniosek;

		public Formularz_PrzejrzyjRaportzPodejrzanejTransakcji(){

		}

		~Formularz_PrzejrzyjRaportzPodejrzanejTransakcji(){

		}

		public void przejrzyjRaportZPodejrzanejTransakcji(){

		}

		public Ster_PrzejrzyjRaportzPodejrzanejTransakcji Ster_PrzejrzyjRaportzPodejrzanejTransakcji{
			get{
				return m_Ster_PrzejrzyjRaportzPodejrzanejTransakcji;
			}
			set{
				m_Ster_PrzejrzyjRaportzPodejrzanejTransakcji = value;
			}
		}

	}//end Formularz_PrzejrzyjRaportzPodejrzanejTransakcji

}//end namespace Interfejsy