///////////////////////////////////////////////////////////
//  Formularz_WydajOpinieAnalityczna.cs
//  Implementation of the Class Formularz_WydajOpinieAnalityczna
//  Generated by Enterprise Architect
//  Created on:      03-kwi-2023 02:07:03
//  Original author: Marcin Kurzawski
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



namespace Interfejsy {
	public class Formularz_WydajOpinieAnalityczna {

		private char idWniosek;
		private int opinia;

		public Formularz_WydajOpinieAnalityczna(){

		}

		~Formularz_WydajOpinieAnalityczna(){

		}

		public Ster_Wydajopinieanalityczna Ster_Wydajopinieanalityczna{
			get{
				return m_Ster_Wydajopinieanalityczna;
			}
			set{
				m_Ster_Wydajopinieanalityczna = value;
			}
		}

		public void wydajOpinieAnalityczna(){

		}

	}//end Formularz_WydajOpinieAnalityczna

}//end namespace Interfejsy