///////////////////////////////////////////////////////////
//  Formularz_ZaakceptujRaport.cs
//  Implementation of the Class Formularz_ZaakceptujRaport
//  Generated by Enterprise Architect
//  Created on:      03-kwi-2023 02:07:26
//  Original author: Marcin Kurzawski
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



namespace Interfejsy {
	public class Formularz_ZaakceptujRaport {

		private char data;
		private char Dodatkowy parametr do raportu;

		public Formularz_ZaakceptujRaport(){

		}

		~Formularz_ZaakceptujRaport(){

		}

		public void podajDaneDoRaportu(){

		}

		public Ster_ZaakceptujRaport Ster_ZaakceptujRaport{
			get{
				return m_Ster_ZaakceptujRaport;
			}
			set{
				m_Ster_ZaakceptujRaport = value;
			}
		}

		public void wczytajRaportDzienny(){

		}

		public void wyswietlRaport(){

		}

		public void zaakceptujRaport(){

		}

	}//end Formularz_ZaakceptujRaport

}//end namespace Interfejsy