///////////////////////////////////////////////////////////
//  Ster_ZapiszDaneoSytuacjiFinansowejKlienta.cs
//  Implementation of the Class Ster_ZapiszDaneoSytuacjiFinansowejKlienta
//  Generated by Enterprise Architect
//  Created on:      06-kwi-2023 23:57:36
//  Original author: Marcin Kurzawski
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public class Ster_ZapiszDaneoSytuacjiFinansowejKlienta {

	private int idWniosek;
	private int informacje;

	public Ster_ZapiszDaneoSytuacjiFinansowejKlienta(){

	}

	~Ster_ZapiszDaneoSytuacjiFinansowejKlienta(){

	}

	public Sytuacja finansowa klienta Sytuacja finansowa klienta{
		get{
			return m_Sytuacja finansowa klienta;
		}
		set{
			m_Sytuacja finansowa klienta = value;
		}
	}

	public void zapiszDaneOSytuacjiFinansowej(){

	}

}//end Ster_ZapiszDaneoSytuacjiFinansowejKlienta