///////////////////////////////////////////////////////////
//  Ster_ObliczScoringKredytowy.cs
//  Implementation of the Class Ster_ObliczScoringKredytowy
//  Generated by Enterprise Architect
//  Created on:      06-kwi-2023 23:49:43
//  Original author: Marcin Kurzawski
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public class Ster_ObliczScoringKredytowy {

	private int idWniosek;

	public Ster_ObliczScoringKredytowy(){

	}

	~Ster_ObliczScoringKredytowy(){

	}

	public void obliczScoring(){

	}

}//end Ster_ObliczScoringKredytowy