///////////////////////////////////////////////////////////
//  Ster_Obliczzdolnosckredytowa.cs
//  Implementation of the Class Ster_Obliczzdolnosckredytowa
//  Generated by Enterprise Architect
//  Created on:      06-kwi-2023 23:56:21
//  Original author: Marcin Kurzawski
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public class Ster_Obliczzdolnosckredytowa {

	private char idWniosek;

	public Ster_Obliczzdolnosckredytowa(){

	}

	~Ster_Obliczzdolnosckredytowa(){

	}

	public void obliczZdolnoscKredytowa(){

	}

	public Zdolnosc kredytowa Zdolnosc kredytowa{
		get{
			return m_Zdolnosc kredytowa;
		}
		set{
			m_Zdolnosc kredytowa = value;
		}
	}

}//end Ster_Obliczzdolnosckredytowa