///////////////////////////////////////////////////////////
//  Ster_ZapiszPlikInformacjeoSytuacjiFinansowejKlienta.cs
//  Implementation of the Class Ster_ZapiszPlikInformacjeoSytuacjiFinansowejKlienta
//  Generated by Enterprise Architect
//  Created on:      06-kwi-2023 23:57:39
//  Original author: Marcin Kurzawski
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public class Ster_ZapiszPlikInformacjeoSytuacjiFinansowejKlienta {

	private int idWNiosek;
	private char Plik umowa kredytowa;

	public Ster_ZapiszPlikInformacjeoSytuacjiFinansowejKlienta(){

	}

	~Ster_ZapiszPlikInformacjeoSytuacjiFinansowejKlienta(){

	}

	public void zapiszPlikInformacjeOSytuacjiFinansowej(){

	}

}//end Ster_ZapiszPlikInformacjeoSytuacjiFinansowejKlienta