///////////////////////////////////////////////////////////
//  Ster_PotwierdzWarunkiKredytu.cs
//  Implementation of the Class Ster_PotwierdzWarunkiKredytu
//  Generated by Enterprise Architect
//  Created on:      06-kwi-2023 23:56:40
//  Original author: Marcin Kurzawski
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public class Ster_PotwierdzWarunkiKredytu {

	private char decyzja;

	public Ster_PotwierdzWarunkiKredytu(){

	}

	~Ster_PotwierdzWarunkiKredytu(){

	}

	public void potwierdzWarunkiKredytu(){

	}

	public Warunki umowy dla klienta Warunki umowy dla klienta{
		get{
			return m_Warunki umowy dla klienta;
		}
		set{
			m_Warunki umowy dla klienta = value;
		}
	}

}//end Ster_PotwierdzWarunkiKredytu